    # The git group in use on some servers is not in Ansible yet so only append.
    - name: set groups for admin(s)
      action: user name={{item}} groups={{admin_groups}} append=yes
      with_items: active_admins

    - name: setup authorized key(s) for root
      authorized_key: user=root key="{{ lookup('file', user_management_ssh_keys_path ~ users[item].public_key ) }}"
      with_items: active_admins
      when: users[item].public_key is defined

    - name: setup additional authorized key(s) for root
      authorized_key: user=root key="{{ lookup('file', user_management_ssh_keys_path ~ users[item].additional_public_key ) }}"
      with_items: active_users
      when: users[item].additional_public_key is defined


    - name: Install package sudo
      action: apt pkg=sudo state=present

    # - name: write the sudoers file
      # action: copy src=../files/sudoers dest=/etc/sudoers
              # owner=root group=root mode=0440
